[package]
name = "cmark-sys"
version = "0.1.0+0.29.0"
authors = ["Connor Kuehl <cipkuehl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.54.0"

[dependencies]
